Pin urlllib3 dependency to <2
Apparently the urllib3 package which we depend on dropped support for
OpenSSL<1.1.1 which causes errors when using cdrouter.py similar to
the following:

    ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168

This commit pins urllib3 to <2 which seems to be the recommended
solution, see https://github.com/urllib3/urllib3/issues/2168.